version: '3.0'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:  
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    ports:
      - 9091:9091
      - 29091:29091
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=101
      - KAFKA_ADVERTISED_HOST_NAME=172.17.0.101
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091,PLAINTEXT_HOST://localhost:29091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS="/kafka/kafka-logs/kafka1"

  kafka2:
     image: confluentinc/cp-kafka:latest
     hostname: kafka2
     container_name: kafka2
     ports:
       - 9092:9092
       - 29092:29092
     depends_on:
       - zookeeper
     environment:
       - KAFKA_BROKER_ID=102
       - KAFKA_ADVERTISED_HOST_NAME172.17.0.102
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
       - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
       - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
       - KAFKA_LOG_DIRS="/kafka/kafka-logs/kafka2"

  kafka3:
     image: confluentinc/cp-kafka:latest
     hostname: kafka3
     container_name: kafka3
     ports:
       - 9093:9093
       - 29093:29093
     depends_on:
       - zookeeper
     environment:
       - KAFKA_BROKER_ID=103
       - KAFKA_ADVERTISED_HOST_NAME=172.17.0.103
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9093,PLAINTEXT_HOST://localhost:29093
       - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
       - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
       - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
       - KAFKA_LOG_DIRS="/kafka/kafka-logs/kafka3"

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    ports:
      - 8181:8181
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS=GET,POST,PUT,OPTIONS
      - SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN='*' 
    links:
      - zookeeper
    depends_on:
      - zookeeper
      - "kafka1"
      - "kafka2"
      - "kafka3"

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
     - "9000:9000"
    environment:
     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
     KAFKA_BROKERCONNECT: "kafka1:9091,kafka2:9092,kafka3:9093"
     SCHEMAREGISTRY_CONNECT: "http://schema-registry:8081"
     JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka1"
      - "kafka2"
      - "kafka3"

networks:
  kafka:
    driver: bridge
  # kafka2:
  #   driver: bridge

#volumes:
  #zookeeper_data:
  #kafka1_data:
  #kafka2_data:
  #postgresVolume:    
