version: '3.0'
services:  
  mysql:    
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mydb
    volumes:
      - "./sql-scripts/:/docker-entrypoint-initdb.d/"

  postgresql:
    image:  postgres:9.6     
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: Welcome123
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db
    ports:
      - "5435:5432"
    volumes:
      - "./postgres-scripts/:/docker-entrypoint-initdb.d/"

